const cryptoCurrencies = [
{label :"Bitcoin", id:1},
{label :"Ethereum", id:2},
{label :" Binance Coin", id:3},
{label : "Tether", id:4},
{label : "Solana", id:5},
{label : "Cardano", id:6},
{label : "XRP", id:7},
{label : "USD Coin", id:8},
{label : "Polkadot", id:9},
{label : "Dogecoin", id:10},
{label : "Avalanche"},
{label : "Terra"},
{label : "Shiba Inu"},
{label : "Crypto.com Coin"},
{label : "Wrapped Bitcoin"},
{label : "Polygon"},
{label : "Litecoin"},
{label : "Binance USD"},
{label :"Algorand"},
{label :"Chainlink"},
{label :"Bitcoin Cash"},
{label : "Uniswap"},
{label :"Dai"},
{label :"Axie Infinity"},
{label :" Stellar"},
{label :"VeChain"},
{label :"TerraUSD"},
{label :"Cosmos"},
{label :"Elrond"},
{label :" Internet Computer"},
{label : "cETH"},
{label :"OKB"},
{label :"Filecoin"},
{label :"TRON"},
{label :"FTX Token"},
{label :"Lido Staked Ether"},
{label :"Theta Network"},
{label :"Hedera"},
{label :"Ethereum Classic"},
{label :"Decentraland"},
{label :"The Sandbox"},
{label :"Fantom"},
{label :"cDAI"},
{label :"Near"},
{label :"Gala",},
{label :"Tezos",},
{label :"The Graph",},
{label :"Monero",},
{label :"Olympus",},
{label :"Klaytn",},
{label :"Helium",},
{label :"EOS",},
{label :"Radix",},
{label :"IOTA",},
{label :"cUSDC",},
{label :"Flow",},
{label :"Magic Internet Money"},
{label :"Kusama",},
{label :"LEO Token",},
{label :"Aave",},
{label :"Loopring",},
{label :"PancakeSwap",},
{label :"THORChain",},
{label :"Enjin Coin",},
{label :"eCash",},
{label :"Stacks",},
{label :"Arweave",},
{label :"Amp",},
{label :"Kadena",},
{label :"Harmony",},
{label :"Bitcoin SV",},
{label :"Maker",},
{label :"Quant",},
{label :"Zcash",},
{label :"NEO",},
{label :"Chiliz",},
{label :"Huobi BTC",},
{label :"Waves",},
{label :"Basic Attention Token"},
{label :"Holo",},
{label :"BitTorrent",},
{label : "KuCoin Token",},
{label : "Bitcoin Cash ABC",},
{label :"Theta Fuel",},
{label :"Curve DAO Token",},
{label :"Dash",},
{label :"Celo",},
{label :"Wonderland",},
{label :"Celsius Network",},
{label :"LINK",},
{label :"Compound",},
{label :"e-Radix",},
{label :"Qtum",},
{label :"NEM",},
{label :"NEXO",},
{label :"Marinade staked SOL"},
{label :"Huobi Token"},
{label :"ECOMI",},
{label :"Sushi",},
{label :"SafeMoon"}
]
export default cryptoCurrencies